import Head from 'next/head'
import { HomePage } from './HomePage'

export default function Home() {
  return (
    <div className="App">
      <Head>
        <title>Farkas Balázs</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="https://i.postimg.cc/g0NZ5nqV/VP-logos-white.png" /> */}
      </Head>

      <body>
        <HomePage />
      </body>

    </div>
  )
}
