import Head from 'next/head'
import ParticlesBg from "./ParticlesBg.jsx"
import Nav from './Home/Nav.jsx'
import HomePage from './Home/HomePage.jsx'
import Icons from './Home/Icons.jsx'
import Projects from './Projects/Projects.jsx'
import CV from './CV/CV.jsx'
import About from './About/About.jsx'
import Contact from './Contact/Contact.jsx'

export default function Home(){
  return (
    <div className="App">
      <Head>
        <title>Farkas Balázs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous" />
      </Head>
      <div className="bg2"></div>
      <ParticlesBg />
      <Nav />
      <HomePage />
      <Icons />
      <Projects />
      <CV />
      <About />
      <Contact />
    </div>
  )
}